version: 2
updates:
  - package-ecosystem: gomod
    directory: /go
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      go-patch-minor:
        applies-to: version-updates
        update-types:
          - patch
          - minor

  - package-ecosystem: cargo
    directory: /rust
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      rust-patch-minor:
        applies-to: version-updates
        update-types:
          - patch
          - minor

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      actions-updates:
        applies-to: version-updates
        update-types:
          - patch
          - minor
          - major
